### ISSUE TITLE
output seems to be invalid

### ISSUE THREAD

**Issue by shahid1996** [mazen160/server-status_PWN#4]
when i execute python server-status_PWN --url 'http://www.example.com/server-status' it gives error like output seems to be invalid.

**Comment by mazen160** [comment]
@shahid1996 Can you please share output message and more details on the error?

**Comment by ramondunker** [comment]
I have the same issue. It keeps saying: "list index out of range"

**Comment by aroly** [comment]
Hello,

I had a similar issue this morning, and found the cause. The "server-status" page I was trying to monitor have an extra HTML `<table>` before the main content. In my case, it contains the "Threads" information. 

The script has an hardcoded index for the table to parse to get the results (here: https://github.com/mazen160/server-status_PWN/blob/master/server-status_PWN.py#L181):

```
        try:
            table_index_id = 0
            VHOST_index_id = -2
```

and in this case it tries to parse the Threads table instead of the table showing the VHost, URI, ...

For me, changing the `table_index_id` from 0 to 1 (in order to parse the second table) fixed it, but it will obviously break the script  if there is not Threads table. I guess a better solution would be to search for the correct table by parsing the content. 

@mazen160 Nice work with this script, I use it from time to time and it's really useful :)

**Comment by mazen160** [comment]
@aroly Thank you for the help on this ticket! Yes, parsing the content and to find the correct indexes would the best solution for the long-term, for the current time, I just documented the issue on README at https://github.com/mazen160/server-status_PWN#note

If anyone would to work on a PR for it, would be happy to have it!
