### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by ramondunker** [mazen160/server-status_PWN#7]
Hi there,

I've tried using this script but it doesn't seem to work for me. When executing a non-debug command I get the following result:
```
python3 server-status_PWN.py --url 'http://127.0.0.1/server-status' -o server_status.txt --enable-full-logging
[#] Requesting.
[#] Requesting.
[#] Requesting.
[#] Requesting.
[#] Requesting.
[#] Requesting.
[New URL]:  http://4
[New Client]: 6
```

When executing with debug enabled I get the following result:
```
python3 server-status_PWN.py --url 'http://127.0.0.1/server-status' -o server_status.txt --enable-full-logging --debug
[#] Requesting.
list index out of range
list index out of range
list index out of range
list index out of range
[New Client]: 8
[#] Requesting.
list index out of range
list index out of range
list index out of range
list index out of range
[New Client]: 7
[#] Requesting.
list index out of range
list index out of range
list index out of range
list index out of range
[#] Requesting.
list index out of range
list index out of range
list index out of range
list index out of range
[#] Requesting.
list index out of range
list index out of range
list index out of range
list index out of range
[#] Requesting.
list index out of range
list index out of range
list index out of range
list index out of range
[#] Requesting.
list index out of range
list index out of range
list index out of range
list index out of range
```

When using Python2 I get the same results.

**Comment by ramondunker** [comment]
Maybe its because of a dependency upgrade?

**Comment by aroly** [comment]
Hello,

I had a similar issue this morning, and found the cause. The "server-status" page I was trying to monitor have an extra HTML `<table>` before the main content. In my case, it contains the "Threads" information. 

The script has an hardcoded index for the table to parse to get the results (here: https://github.com/mazen160/server-status_PWN/blob/master/server-status_PWN.py#L181):

```
        try:
            table_index_id = 0
            VHOST_index_id = -2
```

and in this case it tries to parse the Threads table instead of the table showing the VHost, URI, ...

For me, changing the `table_index_id` from 0 to 1 (in order to parse the second table) fixed it, but it will obviously break the script  if there is not Threads table. I guess a better solution would be to search for the correct table by parsing the content. 

@mazen160 Nice work with this script, I use it from time to time and it's really useful :)

**Comment by ramondunker** [comment]
Hi @aroly,

Thanks for your reply :)

Indeed I'd like to get it working to as it seems a very useful tool. At first I used curl and grep for this kind of monitoring but this seems way better!

**Comment by ramondunker** [comment]
After changing the indexes and waiting a bit everything worked out. Thanks alot for your nudge in the right direction @aroly and thank you for your great work on this script @mazen160 !

**Comment by mazen160** [comment]
@ramondunker :green_heart:
